const posts = [
  {
    category_id: 1,
    title: "Yard Sale - Furniture & Decor",
    body: "Huge yard sale with furniture, lamps, and home decor. Everything must go!",
    price: 0,
    date: "2025-08-15",
    time: "08:00 AM",
    image_url: "https://placehold.co/800x600?text=Yard+Sale",
    address: "335 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0332,
    geolocation_latitude: 29.8789,
  },
  {
    category_id: 1,
    title: "BBQ Cookout Fundraiser",
    body: "Join us for a community BBQ cookout fundraiser. Delicious food and live music!",
    price: 15,
    date: "2025-08-20",
    time: "12:00 PM",
    image_url: "https://placehold.co/800x600?text=BBQ+Cookout",
    address: "329 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0334,
    geolocation_latitude: 29.8787,
  },
  {
    category_id: 1,
    title: "Local Craft Fair",
    body: "Browse handmade crafts, jewelry, and art from local makers.",
    price: 5,
    date: "2025-09-05",
    time: "10:00 AM",
    image_url: "https://placehold.co/800x600?text=Craft+Fair",
    address: "340 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0331,
    geolocation_latitude: 29.8791,
  },
  {
    category_id: 1,
    title: "Community Car Wash",
    body: "Support our local youth group by bringing your car for a wash!",
    price: 10,
    date: "2025-08-18",
    time: "09:00 AM",
    image_url: "https://placehold.co/800x600?text=Car+Wash",
    address: "345 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0333,
    geolocation_latitude: 29.8792,
  },
  {
    category_id: 1,
    title: "Farmers Market",
    body: "Fresh produce, baked goods, and artisan foods from local farmers.",
    price: 0,
    date: "2025-08-22",
    time: "07:30 AM",
    image_url: "https://placehold.co/800x600?text=Farmers+Market",
    address: "350 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0335,
    geolocation_latitude: 29.879,
  },
  {
    category_id: 2,
    title: "Book Swap Event",
    body: "Bring a book, take a book! Free community reading event.",
    price: 0,
    date: "2025-08-25",
    time: "11:00 AM",
    image_url: "https://placehold.co/800x600?text=Book+Swap",
    address: "355 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.033,
    geolocation_latitude: 29.8788,
  },
  {
    category_id: 2,
    title: "Outdoor Movie Night",
    body: "Family-friendly movie night under the stars. Bring blankets and snacks.",
    price: 3,
    date: "2025-08-28",
    time: "08:30 PM",
    image_url: "https://placehold.co/800x600?text=Movie+Night",
    address: "360 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0329,
    geolocation_latitude: 29.8793,
  },
  {
    category_id: 2,
    title: "Garage Band Live",
    body: "Local garage band playing rock classics in the neighborhood park.",
    price: 8,
    date: "2025-09-02",
    time: "06:00 PM",
    image_url: "https://placehold.co/800x600?text=Live+Music",
    address: "365 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0336,
    geolocation_latitude: 29.8786,
  },
  {
    category_id: 2,
    title: "Pet Adoption Day",
    body: "Adopt a furry friend! Cats, dogs, and small pets available.",
    price: 50,
    date: "2025-09-07",
    time: "10:00 AM",
    image_url: "https://placehold.co/800x600?text=Pet+Adoption",
    address: "370 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0338,
    geolocation_latitude: 29.8794,
  },
  {
    category_id: 2,
    title: "Neighborhood Cleanup",
    body: "Join your neighbors in cleaning up our streets and parks.",
    price: 0,
    date: "2025-09-10",
    time: "09:00 AM",
    image_url: "https://placehold.co/800x600?text=Cleanup+Day",
    address: "375 Cottonwood Drive",
    country: "USA",
    state: "LA",
    city: "Gretna",
    zip_code: "70056",
    geolocation_longitude: -90.0337,
    geolocation_latitude: 29.8795,
  },
];

export default posts;
